### PR TITLE
implement rmw_get_topic_names_and_types

### PR DESCRIPTION
**Pull request by michielb-prismtech**
implemented based on rmw_connext implementation

### CODE REVIEW

**Comment by dirk-thomas** [comment]
[Build Status](http://ci.ros2.org/job/ci_linux/3113/)

**Comment by dirk-thomas** [comment]
This seems to make the `test_graph` test pass :clap:

Currently it fails one of the linter tests (http://ci.ros2.org/job/ci_linux/3113/testReport/junit/rmw_opensplice_cpp/uncrustify/src_rmw_topic_names_and_types_cpp/). Once that is resolved this can be merged and we are one step closer to making it green.

**Comment by michielb-prismtech** [comment]
Glad it did, fixed this locally forgot to add the fix to the branch before pushing was a printf statement which did not belong in the final version

**Comment by dirk-thomas** [comment]
After the merge you might also want to delete the branch if it is not needed anymore.

**Pull request merged**
