### PR TITLE
modify licence format to pass linter

### PR DESCRIPTION
**Pull request by mikaelarguedas**
@michielb-prismtech Note that I had to replace "TO_YEAR" with a valid number so I put this year, feel free to make changes directly on this branch,

### CODE REVIEW

**Comment by dirk-thomas** [comment]
[Build Status](http://ci.ros2.org/job/ci_linux/3098/)

**Comment by dirk-thomas** [comment]
We will leave it up to you @michielb-prismtech to (update and) merge this.

**Comment by michielb-prismtech** [comment]
Think it's ok, but have to verify with our legal department.

**Comment by dirk-thomas** [comment]
With all the other PRs merged I triggered two new builds (using the branch of this PR):

* Only with OpenSplice which will hopefully be green: [Build Status](http://ci.ros2.org/job/ci_linux/3130/)

* All three rmw impl. (OpenSplice, FastRTPS, Connext) which will also run the cross vendor communication tests: [Build Status](http://ci.ros2.org/job/ci_linux/3131/)

**Comment by mikaelarguedas** [comment]
:tada: all green including all the cross vendor communication tests :tada:

**Comment by michielb-prismtech** [comment]
Legal approved, so merged

**Pull request merged**
