### PR TITLE
split functions.cpp into separate files

### PR DESCRIPTION
**Pull request by dirk-thomas**
The code has only been moved but not modified (except visibility).

http://ci.ros2.org/job/ros2_batch_ci_linux/548/
http://ci.ros2.org/job/ros2_batch_ci_osx/416/
http://ci.ros2.org/job/ros2_batch_ci_windows/565/

### CODE REVIEW

**Comment by esteve** [comment]
I think it'd look more structured if functions were split by category (e.g. `subscription.cpp` contains `rmw_create_subscription` and `rmw_destroy_subscription`)

**Comment by dirk-thomas** [comment]
@esteve Do you suggest to put each pair of `rmw_create_X` and `rmw_destroy_X` functions into a `.cpp` file? Or are there any other functions you would group?

I would suggest calling it `rmw_X` then in order to clearly distinguish between functions defined in the `rmw` interface and other helper functions.

**Comment by esteve** [comment]
On Wed, Nov 4, 2015 at 4:04 PM, Dirk Thomas <notifications@github.com>
wrote:

> @esteve <https://github.com/esteve> Do you suggest to put each pair of
> rmw_create_X and rmw_destroy_X functions into a .cpp file? Or are there
> any other functions you would group?
>

Yeah, something like that. And for requests, I'd group `rmw_send_request`
and `rmw_take_request` in `rmw_requests`


> I would suggest calling it rmw_X then in order to clearly distinguish
> between functions defined in the rmw interface and other helper functions.
>

`rmw_X` sounds good.

**Comment by dirk-thomas** [comment]
A new set of passing CI jobs for the merged files:

http://ci.ros2.org/job/ros2_batch_ci_linux/558/
http://ci.ros2.org/job/ros2_batch_ci_osx/427/
http://ci.ros2.org/job/ros2_batch_ci_windows/574/

**Comment by esteve** [comment]
+1

**Comment by dirk-thomas** [comment]
Replaced by #93.

**Pull request closed without merging**
