### PR TITLE
Use matched count to determine server_is_available

### PR DESCRIPTION
**Pull request by michielb-prismtech**
- change the signature of internal server_is_available, removed the count_xxx function pointer
- the server_is_available function now use publication_matched and subscription_matched functions
- DCPSPublication and DCPSSubscription listeners add partition name for discovered topics

### CODE REVIEW

**Comment by dirk-thomas** [comment]
LGTM. Do you want me to trigger a CI build for this? Otherwise please feel free to merge this.

**Comment by michielb-prismtech** [comment]
Yes I like a CI build, tested locally and build fine just like to make sure I don't push anything broken into master

**Comment by dirk-thomas** [comment]
[Build Status](http://ci.ros2.org/job/ci_linux/3068/)

**Comment by michielb-prismtech** [comment]
I agree, the current listener implementation adds the topic_names (incl partition) to a list and the count functions return the count of publishers/subscribers based on the topic_name match with the list. This check is incomplete, QoS also needs to be compatible in order to count matches. 
Following functions are used to get the count:
```
rmw_ret_t rmw_count_subscribers(const rmw_node_t * node, const char * topic_name, size_t * count);
rmw_ret_t rmw_count_publishers(const rmw_node_t * node,  const char * topic_name, size_t * count);
```
I suggest adding new functions (and maybe even remove the previous count functions)
```
rmw_ret_t rmw_subscriber_count(const rmw_subscriber_t *, size_t *);
rmw_ret_t rmw_publisher_count(const rmw_publisher_t *, size_t *);
```
with these function you could then get the actual number of matching publishers/subscribers. Extra information available in the get_publication_matched_status() could also be added.

**Comment by dirk-thomas** [comment]
It would indeed be good to add this to the `rmw` API. I created a ticket based on your earlier feedback: ros2/rmw#120.

I am not sure if you would like to contribute this addition to the `rmw` interface as well as expose these functions afterwards in `rcl*`?

**Comment by michielb-prismtech** [comment]
I can, but first need to make sure that the beta3-release fixes for opensplice are ready.

**Comment by michielb-prismtech** [comment]
Think I should have rebased instead

**Comment by dirk-thomas** [comment]
> I can, but first need to make sure that the beta3-release fixes for opensplice are ready.

Absolutely. Before you look at the `rmw` ticket please comment there so other are aware of it to avoid duplicate efforts.

**Pull request merged**
