### PR TITLE
Enforce localhost restriction (#296).

### PR DESCRIPTION
**Pull request by martinbremmer**
Use network interface "127.0.0.1" when in localhost-only mode.

See #296 for more information.

### CODE REVIEW

**Comment by martinbremmer** [comment]
This needs https://github.com/ros2/rosidl_typesupport_opensplice/pull/45 for it to actually work.

**Comment by wjwwood** [comment]
@gonzodepedro can you triage this by running CI?

**Comment by gonzodepedro** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9048/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4798/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7396/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8976/)

**Comment by gonzodepedro** [comment]
Code looks good to me.

**Review by gonzodepedro — COMMENTED** [review]
LGTM

**Comment by dirk-thomas** [comment]
OpenSplice support has been dropped for Foxy so there is no need to iterate on this.

**Comment by clalancette** [comment]
Closing since we no longer support Opensplice in any active ROS 2 distribution.

**Pull request closed without merging**
