### PR TITLE
redirect logging to stdout / stderr instead of files

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connects to ros2/system_tests#7

@esteve @tfoote @wjwwood Please review.

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
lgtm, I guess you actually tried this out already?

One thought is that ospl routinely outputs lots of stuff even in normal operating conditions. This might ok for now, but will quickly become distracting when users are running our examples.

**Comment by dirk-thomas** [comment]
It didn't generate the `ospl-info.log` / `ospl-error.log` files anymore :wink:

**Comment by wjwwood** [comment]
Yeah... this was my concern:

```
william@farl ~/ros2
% ./install/bin/talker__rmw_opensplice_cpp
Publishing: 'Hello World: 1'
Publishing: 'Hello World: 2'
Publishing: 'Hello World: 3'
Publishing: 'Hello World: 4'
Publishing: 'Hello World: 5'
^Csignal_handler(2)

william@farl ~/ros2
% OSPL_INFOFILE="<stdout>" ./install/bin/talker__rmw_opensplice_cpp
========================================================================================
Report      : INFO
Date        : Tue Jun 09 16:47:41 PDT 2015
Description : u_domainNew:Database allocated on heap
Node        : farl
Process     : talker__rmw_opensplice_cpp <12133>
Thread      : spliced 106c2c000
Internals   : V6.4.140407OSS///user::u_domain::u_domainNew/u_domain.c/706/0/1433893661.658201000
========================================================================================
Report      : INFO
Date        : Tue Jun 09 16:47:41 PDT 2015
Description : ---------------------------------------------------------------
              -- The service is using the following configuration settings --
              ---------------------------------------------------------------
              Domain (id)          : ospl_sp_ddsi (0)
              Storage              : 10240 Kbytes
              Storage threshold    : 1024 Kbytes
              Storage address      : Not available
              Locking              : default
              Memory mode          : Heap memory
              Builtin topics       : true
              Priority inheritance : false
Node        : farl
Process     : talker__rmw_opensplice_cpp <12133>
Thread      : spliced 106c2c000
Internals   : V6.4.140407OSS///The OpenSplice domain service/u_domain.c/827/0/1433893661.663104000
========================================================================================
Report      : INFO
Date        : Tue Jun 09 16:47:41 PDT 2015
Description : Service cmsoap disabled
Node        : farl
Process     : talker__rmw_opensplice_cpp <12133>
Thread      : spliced 106c2c000
Internals   : V6.4.140407OSS///OpenSplice domain service/sr_componentInfo.c/439/0/1433893661.663353000
========================================================================================
Report      : INFO
Date        : Tue Jun 09 16:47:41 PDT 2015
Description : ++++++++++++++++++++++++++++++++++++++++++++++++
              ++ The service 'splicedaemon' is now operational.
              ++++++++++++++++++++++++++++++++++++++++++++++++
Node        : farl
Process     : talker__rmw_opensplice_cpp <12133>
Thread      : spliced 106c2c000
Internals   : V6.4.140407OSS///v_serviceChangeState/v_service.c/329/0/1433893661.663675000
========================================================================================
Report      : INFO
Date        : Tue Jun 09 16:47:41 PDT 2015
Description : ++++++++++++++++++++++++++++++++++++++++++++++++
              ++ The service 'ddsi2' is now operational.
              ++++++++++++++++++++++++++++++++++++++++++++++++
Node        : farl
Process     : talker__rmw_opensplice_cpp <12133>
Thread      : ddsi2 10714a000
Internals   : V6.4.140407OSS///v_serviceChangeState/v_service.c/329/0/1433893661.669856000
========================================================================================
Report      : INFO
Date        : Tue Jun 09 16:47:41 PDT 2015
Description : The durability service can by identified by ID: 2146304398
Node        : farl
Process     : talker__rmw_opensplice_cpp <12133>
Thread      : durability 107047000
Internals   : V6.4.140407OSS///DurabilityService/d_durability.c/476/0/1433893661.674603000
Publishing: 'Hello World: 1'
Publishing: 'Hello World: 2'
Publishing: 'Hello World: 3'
Publishing: 'Hello World: 4'
Publishing: 'Hello World: 5'
^Csignal_handler(2)
========================================================================================
Report      : INFO
Date        : Tue Jun 09 16:47:45 PDT 2015
Description : Termination request (signal 2) received from PID 12133 (self), UID 501
Node        : farl
Process     : talker__rmw_opensplice_cpp <12133>
Thread      : signalHandler 106be9000
Internals   : V6.4.140407OSS///signalHandlerThread/os_signalHandler.c/503/0/1433893665.168395000
```

It is _really_ noisy... Maybe we should consider only setting this on the build farm or only when testing (if we can find a good way to do that).

**Comment by tfoote** [comment]
That is very noisy. I think setting it on the buildfarm is cleaner. With that much content it will be very hard to find your own console outputs.

**Comment by dirk-thomas** [comment]
Then lets ignore info message and only output warnings or higher by setting `OSPL_VERBOSITY=2`.

**Comment by wjwwood** [comment]
That seems reasonable to me:

```
william@farl ~/ros2
% ./install/bin/talker__rmw_opensplice_cpp
Publishing: 'Hello World: 1'
Publishing: 'Hello World: 2'
Publishing: 'Hello World: 3'
Publishing: 'Hello World: 4'
Publishing: 'Hello World: 5'
^Csignal_handler(2)

william@farl ~/ros2
% OSPL_VERBOSITY=2 OSPL_INFOFILE="<stdout>" ./install/bin/talker__rmw_opensplice_cpp
Publishing: 'Hello World: 1'
Publishing: 'Hello World: 2'
Publishing: 'Hello World: 3'
Publishing: 'Hello World: 4'
Publishing: 'Hello World: 5'
^Csignal_handler(2)
```

Conveniently on a subsequent run I randomly got some weird warnings:

```
william@farl ~/ros2
% OSPL_VERBOSITY=2 OSPL_INFOFILE="<stdout>" ./install/bin/talker__rmw_opensplice_cpp
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:51 PDT 2015
Description : malformed packet received from vendor 1.1 state parse:shortmsg <52545053 02010101 5344444e 474e4950 @0x14 > (note: maybe partially bswap'd)

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : recv 10b2df000
Internals   : V6.4.140407OSS///ddsi2/q_receive.c/2403/0/1433896491.851305000
Publishing: 'Hello World: 1'
Publishing: 'Hello World: 2'
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:53 PDT 2015
Description : SPDP (vendor 1.1): invalid qos/parameters

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : dq.builtins 10b216000
Internals   : V6.4.140407OSS///ddsi2/q_ddsi_discovery.c/683/0/1433896493.869072000
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:53 PDT 2015
Description : malformed packet received from vendor 1.1 state header <52545058 02010101 ac170192 00009953 00000001 09010800 2e867755 aea4dc49> (note: maybe partially bswap'd)

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : recv 10b2df000
Internals   : V6.4.140407OSS///ddsi2/q_receive.c/2297/0/1433896493.870313000
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:53 PDT 2015
Description : SPDP (vendor 1.1): invalid qos/parameters

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : dq.builtins 10b216000
Internals   : V6.4.140407OSS///ddsi2/q_ddsi_discovery.c/683/0/1433896493.871376000
Publishing: 'Hello World: 3'
Publishing: 'Hello World: 4'
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:54 PDT 2015
Description : SPDP (vendor 1.1): invalid qos/parameters

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : dq.builtins 10b216000
Internals   : V6.4.140407OSS///ddsi2/q_ddsi_discovery.c/683/0/1433896494.892558000
Publishing: 'Hello World: 5'
Publishing: 'Hello World: 6'
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:55 PDT 2015
Description : SPDP (vendor 1.1): invalid qos/parameters

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : dq.builtins 10b216000
Internals   : V6.4.140407OSS///ddsi2/q_ddsi_discovery.c/683/0/1433896495.915199000
Publishing: 'Hello World: 7'
Publishing: 'Hello World: 8'
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:56 PDT 2015
Description : SPDP (vendor 1.1): invalid qos/parameters

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : dq.builtins 10b216000
Internals   : V6.4.140407OSS///ddsi2/q_ddsi_discovery.c/683/0/1433896496.939014000
Publishing: 'Hello World: 9'
Publishing: 'Hello World: 10'
========================================================================================
Report      : WARNING
Date        : Tue Jun 09 17:34:57 PDT 2015
Description : SPDP (vendor 1.1): invalid qos/parameters

Node        : farl
Process     : talker__rmw_opensplice_cpp <16748>
Thread      : dq.builtins 10b216000
Internals   : V6.4.140407OSS///ddsi2/q_ddsi_discovery.c/683/0/1433896497.963171000
Publishing: 'Hello World: 11'
^Csignal_handler(2)
```

+1

**Comment by wjwwood** [comment]
Actually, I think this may have coincided with the running of one of the Connext/OpenSplice demos because now I see those warnings in my test output (using the environment variables proposed in this pr). Maybe the new version of Connext we are using no longer works with OpenSplice on OS X? It seems to be complaining about malformed discovery packets and invalid qos parameters in the SPDP messages (discovery).

**Comment by wjwwood** [comment]
Either way +1, @tfoote can you re-review? I'd like to get this merged so I can take advantage of this on the farm.

**Comment by tfoote** [comment]
+1

**Pull request merged**
