### PR TITLE
use a common datareader to fetch node info from participants.(#242)

### PR DESCRIPTION
**Pull request by cwyark**
Remove get_discovered_* interface in rmw_node_names.cpp and rmw_node_info_and_types.cpp.
Use a built-in datareader to fetch nodes name from *alive* participants.

Signed-off-by: YuSheng <chester@cwyark.me>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@cwyark Please rebase your branch against the latest state of the target branch in order to run CI.

**Comment by cwyark** [comment]
@dirk-thomas Thanks, I've merge the latest rmw_opensplice master branch into my branch.

**Comment by dirk-thomas** [comment]
CI builds using this branch:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7745/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3848/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6338/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7601/)

CI builds using master (to ensure all the failing tests are already present on master):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7762/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3858/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6345/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7609/)

**Comment by dirk-thomas** [comment]
Thanks for the contribution.

**Pull request merged**
