### PR TITLE
Initial rmw_get_service_names_and_types

### PR DESCRIPTION
**Pull request by michielb-prismtech**
Just an initial implementation not yet tested.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
We haven't tagged the Beta 3 release yet but are planning to do so today. What is the state of this? Have you had a chance to test this?

**Comment by michielb-prismtech** [comment]
I've found that the implementation did not work, I've fixed it. However I've not been able to run the complete testsuite yet. My hope is that the CI test run doesn't show any failures.

**Comment by dirk-thomas** [comment]
@michielb-prismtech This PR currently lacks the new file `src/demangle.cpp`. Once you have added that I can trigger new CI builds.

**Comment by michielb-prismtech** [comment]
typed my message before I pushed, will do it other way around next time.

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3230/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3292/)

If the CI builds pass green are you confident to merge this change for Beta 3 (since we are pretty late in the testing phase). Merging it has the (+) that it aims to support the service introspection. On the (-) side there is a chance of regression with any patch (we won't have time to run another round of testing before cutting the release today). I am ok with merging it if you think that is the right thing.

**Comment by michielb-prismtech** [comment]
I wait for the results before answering that question ;)

**Comment by michielb-prismtech** [comment]
Test results look good, if you agree with the changes I'm confident the fix is good. Moved some functions to new files copied two from connext and implemented a get_service_names_and_types function which did not function before. Greatest risk is the newly implemented function but as it didn't function before it's not a big risk

**Comment by dirk-thomas** [comment]
Sounds good to me: :ship:

Thank you for your effort on this!

**Pull request merged**
