### PR TITLE
fix returning loan

### PR DESCRIPTION
**Pull request by dirk-thomas**
As suggested by @wjwwood in https://github.com/ros2/examples/issues/102#issuecomment-224172321

I can confirm that it fixes the problem mentioned in https://github.com/ros2/examples/issues/102#issuecomment-222859255

Running CI for this might not make much sense since it won't show if the patch has the intended effect.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I can confirm that it fixes the problem mentioned in https://github.com/ros2/examples/issues/102#issuecomment-222859255

Running CI for this might not make much sense since it won't show if the patch has the intended effect.

**Comment by wjwwood** [comment]
+1

**Comment by gerkey** [comment]
I wonder whether this fix might help with the cleanup problems identified in #99.

**Comment by tfoote** [comment]
I just pulled and am rebuilding in debug to test #99 and will see if it fixes it.

**Comment by dirk-thomas** [comment]
#99 is still happening for me after 166 iterations.

**Pull request merged**
