### PR TITLE
Fix "ros2 node list" including exited nodes

### PR DESCRIPTION
**Pull request by mm318**
This workaround is for resolving https://github.com/ros2/rmw_opensplice/issues/242 and (at least partially) https://github.com/ros2/ros2/issues/514.

### CODE REVIEW

**Comment by mm318** [comment]
Question to OpenSplice regarding whether or not this is expected behavior opened here: https://github.com/ADLINK-IST/opensplice/issues/79.

**Comment by eboasson** [comment]
Please see https://github.com/ADLINK-IST/opensplice/issues/79

**Comment by mm318** [comment]
Thanks @eboasson!

**Comment by dirk-thomas** [comment]
Since this patch shouldn't be applied as is I will go ahead and close it.

In the [upstream ticket](https://github.com/ADLINK-IST/opensplice/issues/79#issuecomment-456367434) a snippet was provided which should help implementing a patch for this repo. I commented on the [original issue](https://github.com/ros2/rmw_opensplice/issues/242#issuecomment-456472716) to track this.

**Pull request closed without merging**
